/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as basicFevmdalnSol from "./BasicFEVMDALN.sol";
export type { basicFevmdalnSol };
import type * as basicSpnSol from "./BasicSPN.sol";
export type { basicSpnSol };
import type * as spnSol from "./SPN.sol";
export type { spnSol };
